import type { ProjectState } from './types';
import { getClipTypeColor } from './clipTypeColors';
import { createDefaultRecordingSettings } from './recordingSettings';
import { beatsToTicks } from './workflow';
import { BUILTIN_PATCH_TAB_TYPE_IDS } from './patchTabPortContract';
import { createSoundFontPatchTab } from './soundFontPatchTab';
import { createInstrumentPresetParameters } from './instrumentPatchTab';

const toTick = beatsToTicks;

export const sampleProject: ProjectState = {
  name: 'ElpisDAW',
  bpm: 120,
  key: 'A minor',
  status: 'READY',
  isLooping: false,
  selectedPatchTabId: 'midi-edit',
  playheadTick: toTick(18),
  totalTicks: toTick(64),
  gridResolution: '1/8',
  recordingSettings: createDefaultRecordingSettings(),
  selection: { items: [] },
  takes: [],
  patchTabs: [
    {
      id: 'hum-to-midi',
      name: 'Hum to MIDI',
      nodeTypeId: BUILTIN_PATCH_TAB_TYPE_IDS.humToMidi,
      nodeVersion: '1.0.0',
      colorIndex: 0,
      inputType: 'Hum Audio',
      outputType: 'MIDI Notes',
      status: 'ready',
      description: 'Converts the selected hum recording into editable MIDI notes with Basic Pitch.',
      parameters: [
        { id: 'sensitivity', label: 'Pitch Sensitivity', kind: 'slider', min: 0, max: 100, step: 1, value: 72, unit: '%' },
        { id: 'note-range', label: 'Note Range', kind: 'select', value: 'Vocal', options: ['Bass', 'Vocal', 'Lead'] },
      ],
    },
    {
      id: 'midi-edit',
      name: 'MIDI Edit',
      nodeTypeId: BUILTIN_PATCH_TAB_TYPE_IDS.midiEdit,
      nodeVersion: '1.0.0',
      colorIndex: 1,
      inputType: 'MIDI Notes',
      outputType: 'Edited MIDI',
      status: 'processing',
      description: 'Snaps MIDI note starts to the selected grid while preserving note length and velocity.',
      parameters: [
        { id: 'quantize', label: 'Quantize', kind: 'select', value: '1/16', options: ['1/8', '1/16', '1/32', '1/64'] },
      ],
    },
    createSoundFontPatchTab('soundfont', 2),
    {
      id: 'instrument',
      name: 'MIDI TO AUDIO',
      nodeTypeId: BUILTIN_PATCH_TAB_TYPE_IDS.instrument,
      nodeVersion: '1.0.0',
      colorIndex: 3,
      inputType: 'Edited MIDI',
      outputType: 'Instrument Audio',
      status: 'ready',
      description: 'Renders MIDI through the connected built-in or custom SoundFont.',
      inputBindings: [
        { portId: 'midi-in', kind: 'connection', connectionIds: ['c3'] },
        { portId: 'soundfont-in', kind: 'connection', connectionIds: ['c4'] },
      ],
      parameters: createInstrumentPresetParameters(),
    },
  ],
  connections: [
    {
      id: 'c2',
      fromPatchTabId: 'hum-to-midi',
      toPatchTabId: 'midi-edit',
      signalType: 'MIDI Notes',
      order: 0,
      latencyMs: 2,
      enabled: true,
    },
    {
      id: 'c4',
      fromPatchTabId: 'soundfont',
      toPatchTabId: 'instrument',
      fromPortId: 'soundfont-out',
      toPortId: 'soundfont-in',
      activation: 'on',
      createdOrder: 2,
      signalType: 'SOUNDFONT',
      order: 2,
      latencyMs: 0,
      enabled: true,
    },
    {
      id: 'c3',
      fromPatchTabId: 'midi-edit',
      toPatchTabId: 'instrument',
      signalType: 'Edited MIDI',
      order: 1,
      latencyMs: 1,
      enabled: true,
    },
  ],
  tracks: [
    {
      id: 'hum-audio',
      name: 'Hum Audio',
      type: 'audio',
      level: -8,
      clips: [
        {
          id: 'clip-hum-1',
          type: 'hum-audio',
          name: 'Take 01',
          startTick: toTick(4),
          lengthTicks: toTick(12),
          color: getClipTypeColor('hum-audio'),
          generatedBy: 'Microphone Recording',
          createdAt: '2026-06-24T09:00:00.000Z',
          version: 1,
        },
        {
          id: 'clip-hum-2',
          type: 'hum-audio',
          name: 'Hook Hum',
          startTick: toTick(28),
          lengthTicks: toTick(10),
          color: getClipTypeColor('hum-audio'),
          generatedBy: 'Microphone Recording',
          createdAt: '2026-06-24T09:12:00.000Z',
          version: 1,
        },
      ],
    },
    {
      id: 'midi-notes',
      name: 'MIDI Notes',
      type: 'midi',
      level: -6,
      clips: [
        {
          id: 'clip-midi-1',
          type: 'midi-notes',
          name: 'Converted Motif',
          startTick: toTick(6),
          lengthTicks: toTick(18),
          color: getClipTypeColor('midi-notes'),
          sourceClipId: 'clip-hum-1',
          generatedBy: 'Hum to MIDI',
          createdAt: '2026-06-24T09:18:00.000Z',
          version: 1,
        },
        {
          id: 'clip-midi-2',
          type: 'midi-notes',
          name: 'Variation',
          startTick: toTick(34),
          lengthTicks: toTick(14),
          color: getClipTypeColor('midi-notes'),
          sourceClipId: 'clip-hum-2',
          generatedBy: 'Hum to MIDI',
          createdAt: '2026-06-24T09:24:00.000Z',
          version: 1,
        },
      ],
    },
    {
      id: 'instrument-audio',
      name: 'Instrument Audio',
      type: 'audio',
      level: -5,
      clips: [
        {
          id: 'clip-inst-1',
          type: 'instrument-audio',
          name: 'Instrument Print',
          startTick: toTick(8),
          lengthTicks: toTick(24),
          color: getClipTypeColor('instrument-audio'),
          sourceClipId: 'clip-midi-1',
          generatedBy: 'MIDI TO AUDIO',
          createdAt: '2026-06-24T09:31:00.000Z',
          version: 1,
        },
        {
          id: 'clip-inst-2',
          type: 'instrument-audio',
          name: 'Layer Print',
          startTick: toTick(38),
          lengthTicks: toTick(18),
          color: getClipTypeColor('instrument-audio'),
          sourceClipId: 'clip-midi-2',
          generatedBy: 'MIDI TO AUDIO',
          createdAt: '2026-06-24T09:38:00.000Z',
          version: 1,
        },
      ],
    },
    {
      id: 'master',
      name: 'Master',
      type: 'master',
      level: -2,
      clips: [
        {
          id: 'clip-master-1',
          type: 'master',
          name: 'Rough Mix',
          startTick: toTick(0),
          lengthTicks: toTick(56),
          color: getClipTypeColor('master'),
          sourceClipId: 'clip-inst-1',
          generatedBy: 'Clip Filer',
          createdAt: '2026-06-24T09:45:00.000Z',
          version: 1,
        },
      ],
    },
  ],
};
